<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>

    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.1.0+tesseract.0.35.0</Version>
    <TesseractVersion>0.35.0</TesseractVersion>
  </PropertyGroup>
</Project>

