[workspace]
name = "darp-tesseract-native"
channels = ["conda-forge", "tesseract-robotics"]
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
requires-pixi = ">=0.70,<0.71"

[workspace.target.win.build-variants]
c_compiler = ["vs"]
c_compiler_version = ["2026"]
cxx_compiler = ["vs"]
cxx_compiler_version = ["2026"]

[dependencies]
eigen = "==5.0.1"

[feature.bindings.dependencies]
swig = "==4.5.0"

[feature.native.dependencies]
ninja = "*"
cereal = "*"
console_bridge = "*"
tinyxml2 = "*"
yaml-cpp = "*"
assimp = "*"
octomap = "*"
orocos-kdl = "*"
bullet-cpp = "*"
fcl = "*"

[feature.native.target.win-64.dependencies]
cmake = ">=4.4,<5"
vs_win-64 = "2026.*"
libboost-devel = "*"

[feature.native.target.linux-64.dependencies]
boost-cpp = "1.74.*"
cmake = ">=3.21,<3.24"
gxx = "11.*"
libgcc-ng = "11.*"
libstdcxx-ng = "11.*"

[feature.native.target.linux-aarch64.dependencies]
boost-cpp = "1.74.*"
cmake = ">=3.21,<3.24"
gxx = "11.*"
libgcc-ng = "11.*"
libstdcxx-ng = "11.*"

[feature.native.target.osx-64.dependencies]
cmake = ">=4.4,<5"
cxx-compiler = "*"
libboost-devel = "*"

[feature.native.target.osx-arm64.dependencies]
cmake = ">=4.4,<5"
cxx-compiler = "*"
libboost-devel = "*"

[environments]
default = { features = ["native"], solve-group = "native" }
bindings = { features = ["bindings"] }

[tasks]
build-native = "pwsh ./scripts/build_native.ps1"
generate-bindings = "pwsh ./scripts/generate_bindings.ps1"
