<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseLocalProjectReference Condition="'$(UseLocalProjectReference)' == ''">true</UseLocalProjectReference>
    <DarpTesseractNativeVersion Condition="'$(DarpTesseractNativeVersion)' == ''"
      >$(Version)</DarpTesseractNativeVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalProjectReference)' == 'true'">
    <ProjectReference Include="../../src/Darp.Geometry/Darp.Geometry.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalProjectReference)' != 'true'">
    <PackageReference Include="Darp.Geometry" Version="$(DarpTesseractNativeVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Darp.Geometry\Darp.Geometry.csproj" />
  </ItemGroup>
</Project>
